[tool.black]
line-length = 100 # Adjust the line length as you prefer, default is 88
target-version = ['py38', 'py39', 'py310', 'py311'] # set the python versions.
include = '\.pyi?$' # This is a regex for files to include in formatting (default).
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \venv
  | _build
  | buck-out
  | build
  | dist
)/
''' # files to exclude, based on regex.
